#!/usr/bin/env python
import os
import sys
import json
import shutil
import requests
from urlparse import urljoin
from cStringIO import StringIO

BUNDLE_DIR = '/scrapy'
BUNDLE_PATH = os.path.join(BUNDLE_DIR, 'project-slybot.zip')
BUNDLE_URL = 'api/projects/{project}/download/{spider}/'


def download_portia_bundle():
    """ Download Portia bundle to project directory """
    portia_url = os.environ['SHUB_PORTIAURL']
    jobkey = os.environ['SHUB_JOBKEY']
    jobauth = os.environ['SHUB_JOBAUTH']
    spider_id = os.environ.get('SCRAPY_SPIDER', '')
    project_id = jobkey.split('/')[0]

    bundle_url = BUNDLE_URL.format(project=project_id, spider=spider_id)
    headers = {"Authorization": "Bearer {}".format(jobauth),
               "X-Job-Id": jobkey}
    bundle_req = requests.get(
        urljoin(portia_url, bundle_url).strip('/'),
        headers=headers,
        stream=True,
        timeout=300,
    )
    bundle_req.raise_for_status()
    with open(BUNDLE_PATH, 'wb') as outfile:
        shutil.copyfileobj(StringIO(bundle_req.content), outfile)


def update_environment_for_portia():
    """ Modify current environment for Portia """
    env = os.environ.copy()
    env['PROJECT_ZIPFILE'] = BUNDLE_PATH
    env['PROJECT_DIR'] = BUNDLE_DIR
    return env


def main():
    download_portia_bundle()
    env = update_environment_for_portia()
    if len(sys.argv) > 1:
        os.execvpe(sys.argv[1], sys.argv[1:], env)
    else:
        os.execvpe('/bin/bash', ['bash'], env)


if __name__ == '__main__':
    sys.exit(main())
